load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "buffer",
    srcs = [
        "buffer.go",
        "bytes_buffer.go",
        "pool.go",
    ],
    visibility = ["//visibility:public"],
)

go_test(
    name = "buffer_test",
    srcs = [
        "buffer_test.go",
        "bytes_buffer_test.go",
	"pool_test.go",
    ],
    embed = [":buffer"],
    deps = [
        "@com_github_stretchr_testify//assert:assert",
        "@com_github_stretchr_testify//require:require",
    ],
    visibility = ["//:__subpackages__"],
)
